repos:
  - repo: https://github.com/psf/black
    rev: main  # Use the latest version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: main  # Use the latest version
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: main  # Use the latest version
    hooks:
      - id: isort
