# Generated by Django 5.1.2 on 2024-10-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Person", "0002_remove_person_groups_remove_person_is_active_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuredperson",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Person.person",
                verbose_name="Person",
            ),
        ),
    ]
