# Generated by Django 5.1.2 on 2024-10-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Person", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="person",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="person",
            name="password",
        ),
        migrations.RemoveField(
            model_name="person",
            name="user_permissions",
        ),
    ]
